### ISSUE TITLE
Pagination component module.id causes issues for Webpack

### ISSUE THREAD

**Issue by StdVectorBool** [hoveytech/ng2-power-table#3]
Projects built using Webpack can't load the Pagination directive because of these issues:
https://github.com/angular/angular/issues/10626
https://github.com/angular/angular/pull/10595

Webpack uses numeric module.id whereas Angular2 (and probably SystemJS) uses a String.

Since module.id is only needed for [component-relative paths](https://angular.io/docs/ts/latest/cookbook/component-relative-paths.html), any chance you could remove the explicit [module.id from pagination](https://github.com/hoveytech/ng2-power-table/blob/0c870a451b97530147bbad31acf898089c83bdc3/src/Pagination/Pagination.component.ts#L30) since the directive uses an inline template?

**Comment by hoveytech** [comment]
Seems reasonable.
Version 0.1.11 has been published to npm.

**Comment by StdVectorBool** [comment]
Thanks for the speedy response!
