### ISSUE TITLE
Remove typings from postinstall

### ISSUE THREAD

**Issue by hienle-hps** [hoveytech/ng2-power-table#8]
Even though `typings` is listed only as a [development dependency](https://github.com/hoveytech/ng2-power-table/blob/v0.4.2/package.json#L58), it is being invoked when [installing](https://github.com/hoveytech/ng2-power-table/blob/v0.4.2/package.json#L9).  Could this be removed since it causes errors for those who don't have `typings` installed globally?

**Comment by hoveytech** [comment]
Published NuGet package 0.4.3. Removed typings dependency.

**Comment by hienle-hps** [comment]
Thanks for speedy response @dahovey !
